import React from 'react';

import Header from '../Header/Header';
import Footer from '../Footer/Footer';
import  Head  from 'next/head';

const Layout = ({ children }) => {
    return (
        <div>
            <Head>
                <title>Testy | Pitzza</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/assets/images/pizza.png" />
                <link rel="stylesheet" type="text/css" charset="UTF-8" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css" />
                <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css" />
            </Head>
            <Header />

            {children}
            <Footer />
        </div>
    );
}

export default Layout;
